name: Build TtT_ScoreInput

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # 使用するPythonのバージョンを指定

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/fa0311/pyinstaller
        pip install pandas openpyxl

    - name: Build with PyInstaller
      run: |
        pyinstaller TtT_ScoreInput.py --noconsole --onefile --name TtT_ScoreInput

    - name: Clean up build directory
      run: |
        rmdir /s /q build

    - name: Compress dist folder contents
      run: |
        powershell -c "Compress-Archive -Path dist\TtT_ScoreInput.exe -DestinationPath TtT_ScoreInput.zip"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TtT_ScoreInput
        path: TtT_ScoreInput.zip  # 出力されたZIPファイルのパスを指定

    - name: Delete dist directory
      run: |
        rmdir /s /q dist
