name: Build TtT_ScoreInput_macos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # 最新のバージョンに更新

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install Tcl-Tk
      run: |
        brew install tcl-tk
        echo 'export PATH="/usr/local/opt/tcl-tk/bin:$PATH"' >> ~/.bash_profile
        echo 'export LDFLAGS="-L/usr/local/opt/tcl-tk/lib"' >> ~/.bash_profile
        echo 'export CPPFLAGS="-I/usr/local/opt/tcl-tk/include"' >> ~/.bash_profile
        echo 'export PKG_CONFIG_PATH="/usr/local/opt/tcl-tk/lib/pkgconfig"' >> ~/.bash_profile
        source ~/.bash_profile
    
    - name: Install Python 3.12.4 with Tcl-Tk support
      run: |
        brew install pyenv
        export PYTHON_CONFIGURE_OPTS="--with-tcltk-includes='-I/usr/local/opt/tcl-tk/include' --with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6'"
        pyenv install 3.12.4
        pyenv global 3.12.4
    
    - name: Set up Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install git+https://github.com/fa0311/pyinstaller
        pip install pandas openpyxl
    
    - name: Build with PyInstaller
      run: |
        source venv/bin/activate
        pyinstaller --windowed --onefile --osx-bundle-identifier com.example.ttt TtT_ScoreInput.py --name TtT_ScoreInput
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TtT_ScoreInput
        path: dist # distフォルダをアーティファクトとしてアップロード
    
    - name: Clean up build directory
      run: |
        rm -rf build dist
