name: Build TtT_ScoreInput_macos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl git+https://github.com/fa0311/pyinstaller

      - name: Run PyInstaller to build the app
        run: |
          pyinstaller --windowed TtT_ScoreInput.py
          rm -rf build  # build フォルダを削除

      - name: Archive the build output
        uses: actions/upload-artifact@v4
        with:
          name: TtT_ScoreInput
          path: dist/TtT_ScoreInput.app

      - name: Clean up
        run: |
          rm -rf dist  # dist フォルダを削除
