name: Build TtT_ScoreInput_Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # 最新のGLIBCが含まれるUbuntuバージョンを使用

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install git+https://github.com/fa0311/pyinstaller
        pip install pandas openpyxl

    - name: Build with PyInstaller
      run: |
        pyinstaller TtT_ScoreInput.py --noconsole --name TtT_ScoreInput

    - name: Clean up build directory
      run: |
        rm -rf build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TtT_ScoreInput
        path: dist/TtT_ScoreInput

    - name: Delete dist directory
      run: |
        rm -rf dist
