name: Build TtT_ScoreInput_Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # actions/checkoutのバージョンをv4に更新

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # 使用するPythonのバージョンを指定

    - name: Install dependencies
      run: |
        pip install git+https://github.com/fa0311/pyinstaller
        pip install pandas openpyxl

    - name: Build with PyInstaller
      run: |
        pyinstaller TtT_ScoreInput.py --noconsole --name TtT_ScoreInput

    - name: Clean up build directory
      run: |
        rm -rf build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # actions/upload-artifactのバージョンをv4に更新
      with:
        name: TtT_ScoreInput
        path: dist/TtT_ScoreInput  # 出力されたファイルのパスを指定

    - name: Delete dist directory
      run: |
        rm -rf dist
